### ISSUE TITLE
App package name / applicationId ändern

### ISSUE THREAD

**Issue by HeLau1337** [glutter-dev-team/glutter#64]
"Every Android app has a unique application ID that looks like a Java package name, such as com.example.myapp."
https://developer.android.com/studio/build/application-id

Bei uns ist das aktuell noch de.schulenfulda.glutter. 

"**So once you publish your app, you should never change the application ID.**"

Einmalig zu ändern wäre das jetzt unter anderem (!) in 
1. android/app/src/main/AndroidManifest.xml -> `package="de.schulenfulda.glutter"`
2. android/app/build.gradle -> `applicationId "de.schulenfulda.glutter"`
3. ...?

Das scheint noch nicht alles gewesen zu sein, weil ein erster lokaler Test, den package name bei mir zu ändern, fehlgeschlagen ist. "flutter run" bzw. "flutter build" wirft dann diverse Errors/Exceptions. 

(und wo wir dabei sind, können wir den iOS package name dann auch schon mal ändern, auch wenn wir noch keine Lösung für das Veröffentlichen der iOS App haben)

**Comment by MrzJkl** [comment]
Also wäre das bei uns de.glutter.glutter oder wie?

**Comment by HeLau1337** [comment]
Ach so, jetzt wo wir die Domain haben, würde ich sagen ja.
