### ISSUE TITLE
Auf Dashboard- und Monitoring-Screens jeweils erst bei /api/3/pluginslist abfragen, welche Werte überhaupt abfragbar sind

### ISSUE THREAD

**Issue by HeLau1337** [glutter-dev-team/glutter#67]
Anstatt dass z.B. auf dem Dashboard-Screen eine Card mit dem Titel "Sensors" angezeigt wird, der Inhalt darunter aber leer bleibt, weil das aktuell ausgewählte Profile keine Werte für Sensors zurückgibt, sollte die Sensors-Card gar nicht erst angezeigt werden.

**Comment by MrzJkl** [comment]
Dann müssen aber auch alle Entitäten/Modellen von allen verfügbaren Plugins ausprogrammiert werden und die Service-Methoden dafür geschrieben werden. 
Da das ein "größerer" Aufwand ist, würde ich das mal zurückstellen.

**Comment by HeLau1337** [comment]
Öh, ich dachte mir eigentlich einfach nur so was wie:
```
plugins = glancesService.getPluginsList();
if (plugins.contains("sensors")) {
    showSensorsCard();
}
```

Oder geht das nicht so einfach?

**Comment by MrzJkl** [comment]
Ja, wir schreiben vor jede Karte eine Art "Guard". Wenn das Modul nicht verfügbar ist, wird die Karte auch nicht angezeigt.

**Comment by MrzJkl** [comment]
TODO: Methode im GlancesService implementieren, die die Plugins-List läd.
